### ISSUE TITLE
http v2 not supported yet

### ISSUE THREAD

**Issue by infinityhacks** [hamishforbes/lua-resty-upstream#15]
When I test this module, I found a error when sending request over HTTP2.0

`load-balancer.lua:21: Error getting client body reader: http v2 not supported yet, client: 10.10.10.1, server: , request: "GET /favicon.ico HTTP/2.0", host: "www.example.cc"`

This will cause all POST request failed. It seems like the reason is the function **ngx_http_lua_ngx_req_raw_header** and **ngx_http_lua_req_socket** in **lua-nginx-module** do not support SPDY and H2 yet. 

So is there any way to fix this ?

BTW, thank u for this module, I learn a lot from this.

**Comment by hamishforbes** [comment]
Yes the [ngx.req.socket](https://github.com/openresty/lua-nginx-module#ngxreqsocket) feature of ngx_lua does not support HTTP/2 yet.

You're better off raising an issue there as its not something that can be fixed in this module :)

**Comment by infinityhacks** [comment]
Thanks, I have opened a issue in that project
